version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # User requested every 4 months, but maximum supported is monthly.
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
