name: Check Links
on:
  schedule:
    - cron: '0 0 1 * *'  # Monatlich
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --root-dir . --exclude-path "_includes/" --exclude-path "_layouts/" --exclude "\{\{.*\}\}" --exclude "https://scholar.google.de/.*" --exclude "https://www.researchgate.net/.*" --exclude "https://math.codidact.com/.*" --exclude "http://localhost:4000/.*" --accept 200..=206,429,999 './**/*.md' './**/*.html'
