name: Scrape Talk Locations

on:
  push:
    paths:
      - 'talks/**'
      - '_talks/**'
      - 'talkmap.ipynb'
      - 'talkmap.py'
      - '.github/workflows/scrape_talks.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pandas requests beautifulsoup4 geopy python-frontmatter
        pip install getorg --upgrade

    - name: Run Talkmap Script
      run: |
        python talkmap.py

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if ! git diff --cached --quiet; then
          git commit -m "Automated update of talk locations"
          git push
        else
          echo "No changes to commit"
        fi
